// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAhoeGDUpmg__5jvcnk8yjsL6IMfGkmx0A',
    appId: '1:976455618316:web:d848ec10203c67c05a8329',
    messagingSenderId: '976455618316',
    projectId: 'mobcw8',
    authDomain: 'mobcw8.firebaseapp.com',
    storageBucket: 'mobcw8.firebasestorage.app',
    measurementId: 'G-YPWG4TVET7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDh4lfp0F_c4u8osELodrStZzpgdMWPIr4',
    appId: '1:976455618316:android:0d2e4576ac213f715a8329',
    messagingSenderId: '976455618316',
    projectId: 'mobcw8',
    storageBucket: 'mobcw8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBxj4g5L8t3XC2jXzajIbKyhZ1PJZ-JHbw',
    appId: '1:976455618316:ios:61dfa3b6a3a3a7f55a8329',
    messagingSenderId: '976455618316',
    projectId: 'mobcw8',
    storageBucket: 'mobcw8.firebasestorage.app',
    iosBundleId: 'com.example.mobCw8',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBxj4g5L8t3XC2jXzajIbKyhZ1PJZ-JHbw',
    appId: '1:976455618316:ios:61dfa3b6a3a3a7f55a8329',
    messagingSenderId: '976455618316',
    projectId: 'mobcw8',
    storageBucket: 'mobcw8.firebasestorage.app',
    iosBundleId: 'com.example.mobCw8',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAhoeGDUpmg__5jvcnk8yjsL6IMfGkmx0A',
    appId: '1:976455618316:web:e81e4a6d00285f415a8329',
    messagingSenderId: '976455618316',
    projectId: 'mobcw8',
    authDomain: 'mobcw8.firebaseapp.com',
    storageBucket: 'mobcw8.firebasestorage.app',
    measurementId: 'G-GPNP17ZKCC',
  );
}
